# SPDX-License-Identifier: AGPL-3.0-or-later

[advisories]
version = 2
yanked = "warn"
unmaintained = "workspace"
unsound = "workspace"

[bans]
multiple-versions = "allow"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
