// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use anchor_lang::prelude::*;
use crate::errors::*;
use crate::state::*;
use crate::*;

/// Guards for `initialize_protocol_governance`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn initialize_protocol_governance<'info>(ctx: &mut InitializeProtocolGovernance<'info>, args: InitializeProtocolGovernanceArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: args.protocol_fee_bps ≤ 9999
    if !(args.protocol_fee_bps <= 9999) { return Err(OmegaxProtocolError::InvalidBps.into()); }
    // lifecycle: status := Live
    ctx.protocol_governance.status = Status::Live as u8;
    Ok(())
}

/// Guards for `set_protocol_emergency_pause`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn set_protocol_emergency_pause<'info>(ctx: &mut SetProtocolEmergencyPause<'info>, args: SetProtocolEmergencyPauseArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.protocol_governance.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `rotate_protocol_governance_authority`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn rotate_protocol_governance_authority<'info>(ctx: &mut RotateProtocolGovernanceAuthority<'info>, args: RotateProtocolGovernanceAuthorityArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.protocol_governance.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `create_reserve_domain`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_reserve_domain<'info>(ctx: &mut CreateReserveDomain<'info>, args: CreateReserveDomainArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.reserve_domain.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `update_reserve_domain_controls`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn update_reserve_domain_controls<'info>(ctx: &mut UpdateReserveDomainControls<'info>, args: UpdateReserveDomainControlsArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.reserve_domain.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `create_domain_asset_vault`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_domain_asset_vault<'info>(ctx: &mut CreateDomainAssetVault<'info>, args: CreateDomainAssetVaultArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `configure_reserve_asset_rail`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn configure_reserve_asset_rail<'info>(ctx: &mut ConfigureReserveAssetRail<'info>, args: ConfigureReserveAssetRailArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.reserve_asset_rail.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    Ok(())
}

/// Guards for `publish_reserve_asset_rail_price`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn publish_reserve_asset_rail_price<'info>(ctx: &mut PublishReserveAssetRailPrice<'info>, args: PublishReserveAssetRailPriceArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.reserve_asset_rail.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.price_usd_1e8 > 0
    if !(args.price_usd_1e8 > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `init_protocol_fee_vault`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn init_protocol_fee_vault<'info>(ctx: &mut InitProtocolFeeVault<'info>, args: InitProtocolFeeVaultArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.protocol_fee_vault.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `init_pool_treasury_vault`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn init_pool_treasury_vault<'info>(ctx: &mut InitPoolTreasuryVault<'info>, args: InitPoolTreasuryVaultArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.pool_treasury_vault.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `init_pool_oracle_fee_vault`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn init_pool_oracle_fee_vault<'info>(ctx: &mut InitPoolOracleFeeVault<'info>, args: InitPoolOracleFeeVaultArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.pool_oracle_fee_vault.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `create_health_plan`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_health_plan<'info>(ctx: &mut CreateHealthPlan<'info>, args: CreateHealthPlanArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.health_plan.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `update_health_plan_controls`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn update_health_plan_controls<'info>(ctx: &mut UpdateHealthPlanControls<'info>, args: UpdateHealthPlanControlsArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.health_plan.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `create_policy_series`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_policy_series<'info>(ctx: &mut CreatePolicySeries<'info>, args: CreatePolicySeriesArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `initialize_series_reserve_ledger`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn initialize_series_reserve_ledger<'info>(ctx: &mut InitializeSeriesReserveLedger<'info>, args: InitializeSeriesReserveLedgerArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.series_reserve_ledger.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `version_policy_series`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn version_policy_series<'info>(ctx: &mut VersionPolicySeries<'info>, args: VersionPolicySeriesArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `open_member_position`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn open_member_position<'info>(ctx: &mut OpenMemberPosition<'info>, args: OpenMemberPositionArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `update_member_eligibility`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn update_member_eligibility<'info>(ctx: &mut UpdateMemberEligibility<'info>, args: UpdateMemberEligibilityArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.member_position.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `open_funding_line`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn open_funding_line<'info>(ctx: &mut OpenFundingLine<'info>, args: OpenFundingLineArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `fund_sponsor_budget`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn fund_sponsor_budget<'info>(ctx: &mut FundSponsorBudget<'info>, args: FundSponsorBudgetArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `record_premium_payment`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn record_premium_payment<'info>(ctx: &mut RecordPremiumPayment<'info>, args: RecordPremiumPaymentArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `create_commitment_campaign`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_commitment_campaign<'info>(ctx: &mut CreateCommitmentCampaign<'info>, args: CreateCommitmentCampaignArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.deposit_amount > 0
    if !(args.deposit_amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: args.coverage_amount > 0
    if !(args.coverage_amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `create_commitment_payment_rail`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_commitment_payment_rail<'info>(ctx: &mut CreateCommitmentPaymentRail<'info>, args: CreateCommitmentPaymentRailArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.deposit_amount > 0
    if !(args.deposit_amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: args.coverage_amount > 0
    if !(args.coverage_amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `deposit_commitment`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit_commitment<'info>(ctx: &mut DepositCommitment<'info>, args: DepositCommitmentArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    Ok(())
}

/// Guards for `activate_direct_premium_commitment`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn activate_direct_premium_commitment<'info>(ctx: &mut ActivateDirectPremiumCommitment<'info>, args: ActivateCommitmentArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    Ok(())
}

/// Guards for `activate_treasury_credit_commitment`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn activate_treasury_credit_commitment<'info>(ctx: &mut ActivateTreasuryCreditCommitment<'info>, args: ActivateCommitmentArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    Ok(())
}

/// Guards for `activate_waterfall_commitment`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn activate_waterfall_commitment<'info>(ctx: &mut ActivateWaterfallCommitment<'info>, args: ActivateCommitmentArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    Ok(())
}

/// Guards for `refund_commitment`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn refund_commitment<'info>(ctx: &mut RefundCommitment<'info>, args: RefundCommitmentArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `pause_commitment_campaign`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn pause_commitment_campaign<'info>(ctx: &mut PauseCommitmentCampaign<'info>, args: PauseCommitmentCampaignArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.campaign.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    Ok(())
}

/// Guards for `create_obligation`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_obligation<'info>(ctx: &mut CreateObligation<'info>, args: CreateObligationArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `reserve_obligation`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn reserve_obligation<'info>(ctx: &mut ReserveObligation<'info>, args: ReserveObligationArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `settle_obligation`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn settle_obligation<'info>(ctx: &mut SettleObligation<'info>, args: SettleObligationArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `release_reserve`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn release_reserve<'info>(ctx: &mut ReleaseReserve<'info>, args: ReleaseReserveArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `open_claim_case`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn open_claim_case<'info>(ctx: &mut OpenClaimCase<'info>, args: OpenClaimCaseArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.claim_case.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    Ok(())
}

/// Guards for `authorize_claim_recipient`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn authorize_claim_recipient<'info>(ctx: &mut AuthorizeClaimRecipient<'info>, args: AuthorizeClaimRecipientArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.claim_case.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    Ok(())
}

/// Guards for `attach_claim_evidence_ref`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn attach_claim_evidence_ref<'info>(ctx: &mut AttachClaimEvidenceRef<'info>, args: AttachClaimEvidenceRefArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.claim_case.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    Ok(())
}

/// Guards for `adjudicate_claim_case`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn adjudicate_claim_case<'info>(ctx: &mut AdjudicateClaimCase<'info>, args: AdjudicateClaimCaseArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.reserve_amount ≤ args.approved_amount
    if !(args.reserve_amount <= args.approved_amount) { return Err(OmegaxProtocolError::AmountExceedsApprovedClaim.into()); }
    Ok(())
}

/// Guards for `settle_claim_case`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn settle_claim_case<'info>(ctx: &mut SettleClaimCase<'info>, args: SettleClaimCaseArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: paid_amount + args.amount ≤ approved_amount
    if !(paid_amount + args.amount <= approved_amount) { return Err(OmegaxProtocolError::AmountExceedsApprovedClaim.into()); }
    Ok(())
}

/// Guards for `settle_claim_case_selected_asset`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn settle_claim_case_selected_asset<'info>(ctx: &mut SettleClaimCaseSelectedAsset<'info>, args: SettleClaimCaseSelectedAssetArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.claim_credit_amount > 0
    if !(args.claim_credit_amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: args.payout_amount > 0
    if !(args.payout_amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: args.max_overpay_bps ≤ 50
    if !(args.max_overpay_bps <= 50) { return Err(OmegaxProtocolError::SelectedAssetOverpayBpsTooHigh.into()); }
    // requires: paid_amount + args.claim_credit_amount ≤ approved_amount
    if !(paid_amount + args.claim_credit_amount <= approved_amount) { return Err(OmegaxProtocolError::AmountExceedsApprovedClaim.into()); }
    Ok(())
}

/// Guards for `create_liquidity_pool`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_liquidity_pool<'info>(ctx: &mut CreateLiquidityPool<'info>, args: CreateLiquidityPoolArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.liquidity_pool.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    // requires: args.fee_bps ≤ 9999
    if !(args.fee_bps <= 9999) { return Err(OmegaxProtocolError::InvalidBps.into()); }
    Ok(())
}

/// Guards for `create_capital_class`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_capital_class<'info>(ctx: &mut CreateCapitalClass<'info>, args: CreateCapitalClassArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: args.fee_bps ≤ 9999
    if !(args.fee_bps <= 9999) { return Err(OmegaxProtocolError::InvalidBps.into()); }
    Ok(())
}

/// Guards for `update_capital_class_controls`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn update_capital_class_controls<'info>(ctx: &mut UpdateCapitalClassControls<'info>, args: UpdateCapitalClassControlsArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.capital_class.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `update_lp_position_credentialing`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn update_lp_position_credentialing<'info>(ctx: &mut UpdateLpPositionCredentialing<'info>, args: UpdateLpPositionCredentialingArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.lp_position.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `deposit_into_capital_class`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit_into_capital_class<'info>(ctx: &mut DepositIntoCapitalClass<'info>, args: DepositIntoCapitalClassArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `request_redemption`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn request_redemption<'info>(ctx: &mut RequestRedemption<'info>, args: RequestRedemptionArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.shares > 0
    if !(args.shares > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `process_redemption_queue`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn process_redemption_queue<'info>(ctx: &mut ProcessRedemptionQueue<'info>, args: ProcessRedemptionQueueArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.shares > 0
    if !(args.shares > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `withdraw_protocol_fee_spl`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn withdraw_protocol_fee_spl<'info>(ctx: &mut WithdrawProtocolFeeSpl<'info>, args: WithdrawArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: withdrawn_fees + args.amount ≤ accrued_fees
    if !(withdrawn_fees + args.amount <= accrued_fees) { return Err(OmegaxProtocolError::FeeVaultInsufficientBalance.into()); }
    Ok(())
}

/// Guards for `withdraw_protocol_fee_sol`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn withdraw_protocol_fee_sol<'info>(ctx: &mut WithdrawProtocolFeeSol<'info>, args: WithdrawArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: withdrawn_fees + args.amount ≤ accrued_fees
    if !(withdrawn_fees + args.amount <= accrued_fees) { return Err(OmegaxProtocolError::FeeVaultInsufficientBalance.into()); }
    Ok(())
}

/// Guards for `withdraw_pool_treasury_spl`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn withdraw_pool_treasury_spl<'info>(ctx: &mut WithdrawPoolTreasurySpl<'info>, args: WithdrawArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: withdrawn_fees + args.amount ≤ accrued_fees
    if !(withdrawn_fees + args.amount <= accrued_fees) { return Err(OmegaxProtocolError::FeeVaultInsufficientBalance.into()); }
    Ok(())
}

/// Guards for `withdraw_pool_treasury_sol`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn withdraw_pool_treasury_sol<'info>(ctx: &mut WithdrawPoolTreasurySol<'info>, args: WithdrawArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: withdrawn_fees + args.amount ≤ accrued_fees
    if !(withdrawn_fees + args.amount <= accrued_fees) { return Err(OmegaxProtocolError::FeeVaultInsufficientBalance.into()); }
    Ok(())
}

/// Guards for `withdraw_pool_oracle_fee_spl`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn withdraw_pool_oracle_fee_spl<'info>(ctx: &mut WithdrawPoolOracleFeeSpl<'info>, args: WithdrawArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: withdrawn_fees + args.amount ≤ accrued_fees
    if !(withdrawn_fees + args.amount <= accrued_fees) { return Err(OmegaxProtocolError::FeeVaultInsufficientBalance.into()); }
    Ok(())
}

/// Guards for `withdraw_pool_oracle_fee_sol`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn withdraw_pool_oracle_fee_sol<'info>(ctx: &mut WithdrawPoolOracleFeeSol<'info>, args: WithdrawArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: withdrawn_fees + args.amount ≤ accrued_fees
    if !(withdrawn_fees + args.amount <= accrued_fees) { return Err(OmegaxProtocolError::FeeVaultInsufficientBalance.into()); }
    Ok(())
}

/// Guards for `create_allocation_position`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_allocation_position<'info>(ctx: &mut CreateAllocationPosition<'info>, args: CreateAllocationPositionArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `update_allocation_caps`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn update_allocation_caps<'info>(ctx: &mut UpdateAllocationCaps<'info>, args: UpdateAllocationCapsArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.allocation_position.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `allocate_capital`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn allocate_capital<'info>(ctx: &mut AllocateCapital<'info>, args: AllocateCapitalArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `deallocate_capital`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn deallocate_capital<'info>(ctx: &mut DeallocateCapital<'info>, args: DeallocateCapitalArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `mark_impairment`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn mark_impairment<'info>(ctx: &mut MarkImpairment<'info>, args: MarkImpairmentArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `register_oracle`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn register_oracle<'info>(ctx: &mut RegisterOracle<'info>, args: RegisterOracleArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.oracle_profile.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `claim_oracle`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn claim_oracle<'info>(ctx: &mut ClaimOracle<'info>) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.oracle_profile.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `update_oracle_profile`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn update_oracle_profile<'info>(ctx: &mut UpdateOracleProfile<'info>, args: UpdateOracleProfileArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.oracle_profile.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `set_pool_oracle`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn set_pool_oracle<'info>(ctx: &mut SetPoolOracle<'info>, args: SetPoolOracleArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.pool_oracle_approval.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `set_pool_oracle_permissions`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn set_pool_oracle_permissions<'info>(ctx: &mut SetPoolOraclePermissions<'info>, args: SetPoolOraclePermissionsArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.pool_oracle_permission_set.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `set_pool_oracle_policy`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn set_pool_oracle_policy<'info>(ctx: &mut SetPoolOraclePolicy<'info>, args: SetPoolOraclePolicyArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.pool_oracle_policy.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    // requires: args.oracle_fee_bps ≤ 9999
    if !(args.oracle_fee_bps <= 9999) { return Err(OmegaxProtocolError::InvalidBps.into()); }
    Ok(())
}

/// Guards for `register_outcome_schema`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn register_outcome_schema<'info>(ctx: &mut RegisterOutcomeSchema<'info>, args: RegisterOutcomeSchemaArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `verify_outcome_schema`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn verify_outcome_schema<'info>(ctx: &mut VerifyOutcomeSchema<'info>, args: VerifyOutcomeSchemaArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.outcome_schema.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `backfill_schema_dependency_ledger`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn backfill_schema_dependency_ledger<'info>(ctx: &mut BackfillSchemaDependencyLedger<'info>, args: BackfillSchemaDependencyLedgerArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // lifecycle: require status == Live
    if ctx.schema_dependency_ledger.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `close_outcome_schema`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn close_outcome_schema<'info>(ctx: &mut CloseOutcomeSchema<'info>) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `attest_claim_case`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn attest_claim_case<'info>(ctx: &mut AttestClaimCase<'info>, args: AttestClaimCaseArgs) -> Result<()> {
    let emergency_pause = false;
    let paid_amount: u64 = 0;
    let approved_amount: u64 = u64::MAX;
    let withdrawn_fees: u64 = 0;
    let accrued_fees: u64 = u64::MAX;
    // No guards declared in spec — nothing to check.
    Ok(())
}

// ---- END GENERATED ----
