// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:e59de88d73051445
use anchor_lang::prelude::*;

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct ActivateCommitmentArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct AdjudicateClaimCaseArgs {
    pub review_state: u8,
    pub approved_amount: u64,
    pub denied_amount: u64,
    pub reserve_amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct AllocateCapitalArgs {
    pub amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct AttachClaimEvidenceRefArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct AttestClaimCaseArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct AuthorizeClaimRecipientArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct BackfillSchemaDependencyLedgerArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct ConfigureReserveAssetRailArgs {
    pub active: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct CreateAllocationPositionArgs {
    pub cap_amount: u64,
    pub weight_bps: u16,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct CreateCapitalClassArgs {
    pub fee_bps: u16,
    pub pause_flags: u32,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct CreateCommitmentCampaignArgs {
    pub deposit_amount: u64,
    pub coverage_amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct CreateCommitmentPaymentRailArgs {
    pub deposit_amount: u64,
    pub coverage_amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct CreateDomainAssetVaultArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct CreateHealthPlanArgs {
    pub allowed_rail_mask: u16,
    pub pause_flags: u32,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct CreateLiquidityPoolArgs {
    pub fee_bps: u16,
    pub pause_flags: u32,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct CreateObligationArgs {
    pub amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct CreatePolicySeriesArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct CreateReserveDomainArgs {
    pub allowed_rail_mask: u16,
    pub pause_flags: u32,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct DeallocateCapitalArgs {
    pub amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct DepositCommitmentArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct DepositIntoCapitalClassArgs {
    pub amount: u64,
    pub shares: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct FundSponsorBudgetArgs {
    pub amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct InitPoolOracleFeeVaultArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct InitPoolTreasuryVaultArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct InitProtocolFeeVaultArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct InitializeProtocolGovernanceArgs {
    pub protocol_fee_bps: u16,
    pub emergency_pause: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct InitializeSeriesReserveLedgerArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct MarkImpairmentArgs {
    pub amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct OpenClaimCaseArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct OpenFundingLineArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct OpenMemberPositionArgs {
    pub eligibility_status: u8,
    pub delegated_rights: u32,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct PauseCommitmentCampaignArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct ProcessRedemptionQueueArgs {
    pub shares: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct PublishReserveAssetRailPriceArgs {
    pub price_usd_1e8: u64,
    pub confidence_bps: u16,
    pub published_at_ts: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct RecordPremiumPaymentArgs {
    pub amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct RefundCommitmentArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct RegisterOracleArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct RegisterOutcomeSchemaArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct ReleaseReserveArgs {
    pub amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct RequestRedemptionArgs {
    pub shares: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct ReserveObligationArgs {
    pub amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct RotateProtocolGovernanceAuthorityArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct SetPoolOracleArgs {
    pub active: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct SetPoolOraclePermissionsArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct SetPoolOraclePolicyArgs {
    pub quorum_m: u8,
    pub quorum_n: u8,
    pub oracle_fee_bps: u16,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct SetProtocolEmergencyPauseArgs {
    pub emergency_pause: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct SettleClaimCaseArgs {
    pub amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct SettleClaimCaseSelectedAssetArgs {
    pub claim_credit_amount: u64,
    pub payout_amount: u64,
    pub max_overpay_bps: u16,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct SettleObligationArgs {
    pub amount: u64,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct UpdateAllocationCapsArgs {
    pub cap_amount: u64,
    pub weight_bps: u16,
    pub active: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct UpdateCapitalClassControlsArgs {
    pub pause_flags: u32,
    pub queue_only_redemptions: bool,
    pub active: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct UpdateHealthPlanControlsArgs {
    pub allowed_rail_mask: u16,
    pub pause_flags: u32,
    pub active: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct UpdateLpPositionCredentialingArgs {
    pub credentialed: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct UpdateMemberEligibilityArgs {
    pub eligibility_status: u8,
    pub delegated_rights: u32,
    pub active: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct UpdateOracleProfileArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct UpdateReserveDomainControlsArgs {
    pub allowed_rail_mask: u16,
    pub pause_flags: u32,
    pub active: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct VerifyOutcomeSchemaArgs {
    pub verified: bool,
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct VersionPolicySeriesArgs {
}

#[repr(C)]
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct WithdrawArgs {
    pub amount: u64,
}

#[account]
pub struct OmegaxProtocolAccount {
    pub governance_authority: Pubkey,
    pub authority: Pubkey,
    pub plan_admin: Pubkey,
    pub wallet: Pubkey,
    pub depositor: Pubkey,
    pub activation_authority: Pubkey,
    pub owner: Pubkey,
    pub admin: Pubkey,
    pub oracle: Pubkey,
    pub publisher: Pubkey,
    pub audit_nonce: u64,
    pub protocol_fee_bps: u64,
    pub emergency_pause: bool,
    pub allowed_rail_mask: u64,
    pub pause_flags: u64,
    pub active: bool,
    pub total_assets: u64,
    pub last_price_usd_1e8: u64,
    pub last_price_confidence_bps: u64,
    pub last_price_published_at_ts: u64,
    pub accrued_fees: u64,
    pub withdrawn_fees: u64,
    pub membership_mode: u64,
    pub eligibility_status: u64,
    pub delegated_rights: u64,
    pub funded_amount: u64,
    pub spent_amount: u64,
    pub reserved_amount: u64,
    pub paid_amount: u64,
    pub approved_amount: u64,
    pub denied_amount: u64,
    pub pending_amount: u64,
    pub activated_amount: u64,
    pub treasury_locked_amount: u64,
    pub refunded_amount: u64,
    pub canceled_amount: u64,
    pub next_queue_index: u64,
    pub refunded_at: u64,
    pub intake_status: u64,
    pub review_state: u64,
    pub recovered_amount: u64,
    pub appeal_count: u64,
    pub attestation_count: u64,
    pub supported_schema_count: u64,
    pub updated_at_ts: u64,
    pub updated_at: u64,
    pub created_at_ts: u64,
    pub closed_at: u64,
    pub oracle_fee_bps: u64,
    pub quorum_m: u64,
    pub quorum_n: u64,
    pub challenge_window_secs: u64,
    pub cap_amount: u64,
    pub weight_bps: u64,
    pub allocated_amount: u64,
    pub allocated_assets: u64,
    pub total_allocated: u64,
    pub pending_redemption_shares: u64,
    pub pending_redemption_assets: u64,
    pub pending_redemptions: u64,
    pub total_shares: u64,
    pub nav_assets: u64,
    pub queue_only_redemptions: bool,
    pub credentialed: bool,
    pub claimed: bool,
    pub verified: bool,
    pub closed_outcome_schema_count: u64,
    pub commitment_deposit_amount: u64,
    pub refund_amount: u64,
    pub settlement_net_payout_amount: u64,
    pub claim_net_payout_amount: u64,
    pub redemption_net_payout_amount: u64,
    pub fee_withdrawal_amount: u64,
    pub bump: u64,
    pub status: u8,
}

/// Program lifecycle states.
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Status {
    Uninitialized = 0,
    Live = 1,
}
// ---- END GENERATED ----
