// ---- GENERATED BY QEDGEN VIA scripts/run_qedgen.mjs ----
#![cfg(kani)]

const MAX_CONFIGURED_FEE_BPS: u16 = 9999;
const MAX_SELECTED_ASSET_PAYOUT_OVERPAY_BPS: u16 = 50;

#[derive(Clone, Copy, PartialEq, Eq)]
enum Status {
    Uninitialized,
    Live,
}

#[derive(Clone, Copy)]
struct State {
    status: Status,
    protocol_fee_bps: u16,
    emergency_pause: bool,
    paid_amount: u64,
    approved_amount: u64,
    withdrawn_fees: u64,
    accrued_fees: u64,
    audit_nonce: u64,
}

#[derive(Clone, Copy)]
struct InitializeProtocolGovernanceArgs {
    protocol_fee_bps: u16,
    emergency_pause: bool,
}

#[derive(Clone, Copy)]
struct SettleClaimCaseArgs {
    amount: u64,
}

#[derive(Clone, Copy)]
struct SettleClaimCaseSelectedAssetArgs {
    claim_credit_amount: u64,
    payout_amount: u64,
    max_overpay_bps: u16,
}

#[derive(Clone, Copy)]
struct WithdrawArgs {
    amount: u64,
}

fn protocol_fee_bps_bounded(s: &State) -> bool {
    s.protocol_fee_bps <= MAX_CONFIGURED_FEE_BPS
}

fn claim_payment_bounded(s: &State) -> bool {
    s.paid_amount <= s.approved_amount
}

fn fee_withdrawals_bounded(s: &State) -> bool {
    s.withdrawn_fees <= s.accrued_fees
}

fn initialize_protocol_governance(
    s: &mut State,
    args: InitializeProtocolGovernanceArgs,
) -> bool {
    if s.status != Status::Uninitialized || args.protocol_fee_bps > MAX_CONFIGURED_FEE_BPS {
        return false;
    }

    s.status = Status::Live;
    s.protocol_fee_bps = args.protocol_fee_bps;
    s.emergency_pause = args.emergency_pause;
    s.audit_nonce = 0;
    true
}

fn settle_claim_case(s: &mut State, args: SettleClaimCaseArgs) -> bool {
    if s.status != Status::Live
        || s.emergency_pause
        || args.amount == 0
        || s.paid_amount > u64::MAX - 1
        || s.audit_nonce > u64::MAX - 1
        || s.paid_amount > u64::MAX - args.amount
        || s.paid_amount + args.amount > s.approved_amount
    {
        return false;
    }

    s.paid_amount += 1;
    s.audit_nonce += 1;
    true
}

fn settle_claim_case_selected_asset(
    s: &mut State,
    args: SettleClaimCaseSelectedAssetArgs,
) -> bool {
    if s.status != Status::Live
        || s.emergency_pause
        || args.claim_credit_amount == 0
        || args.payout_amount == 0
        || args.max_overpay_bps > MAX_SELECTED_ASSET_PAYOUT_OVERPAY_BPS
        || s.paid_amount > u64::MAX - 1
        || s.audit_nonce > u64::MAX - 1
        || s.paid_amount > u64::MAX - args.claim_credit_amount
        || s.paid_amount + args.claim_credit_amount > s.approved_amount
    {
        return false;
    }

    s.paid_amount += 1;
    s.audit_nonce += 1;
    true
}

fn withdraw_protocol_fee_spl(s: &mut State, args: WithdrawArgs) -> bool {
    if s.status != Status::Live
        || args.amount == 0
        || s.withdrawn_fees > u64::MAX - 1
        || s.audit_nonce > u64::MAX - 1
        || s.withdrawn_fees > u64::MAX - args.amount
        || s.withdrawn_fees + args.amount > s.accrued_fees
    {
        return false;
    }

    s.withdrawn_fees += 1;
    s.audit_nonce += 1;
    true
}

#[kani::proof]
fn initialize_transition_preserves_protocol_fee_bound() {
    let protocol_fee_bps: u16 = kani::any();
    let emergency_pause: bool = kani::any();
    kani::assume(protocol_fee_bps <= MAX_CONFIGURED_FEE_BPS);
    let mut state = State {
        status: Status::Uninitialized,
        protocol_fee_bps: 0,
        emergency_pause: false,
        paid_amount: 0,
        approved_amount: 0,
        withdrawn_fees: 0,
        accrued_fees: 0,
        audit_nonce: kani::any(),
    };
    let args = InitializeProtocolGovernanceArgs { protocol_fee_bps, emergency_pause };

    assert!(initialize_protocol_governance(&mut state, args));
    assert!(protocol_fee_bps_bounded(&state));
}

#[kani::proof]
fn direct_claim_transition_preserves_claim_payment_bound() {
    let paid_amount: u64 = kani::any();
    let approved_amount: u64 = kani::any();
    let amount: u64 = kani::any();
    let audit_nonce: u64 = kani::any();
    kani::assume(amount > 0);
    kani::assume(paid_amount <= u64::MAX - 1);
    kani::assume(audit_nonce <= u64::MAX - 1);
    kani::assume(paid_amount <= approved_amount);
    kani::assume(paid_amount <= u64::MAX - amount);
    kani::assume(paid_amount + amount <= approved_amount);
    let mut state = State {
        status: Status::Live,
        protocol_fee_bps: 0,
        emergency_pause: false,
        paid_amount,
        approved_amount,
        withdrawn_fees: 0,
        accrued_fees: 0,
        audit_nonce,
    };
    let args = SettleClaimCaseArgs { amount };

    assert!(settle_claim_case(&mut state, args));
    assert!(claim_payment_bounded(&state));
}

#[kani::proof]
fn selected_asset_claim_transition_preserves_claim_payment_bound() {
    let paid_amount: u64 = kani::any();
    let approved_amount: u64 = kani::any();
    let claim_credit_amount: u64 = kani::any();
    let payout_amount: u64 = kani::any();
    let max_overpay_bps: u16 = kani::any();
    let audit_nonce: u64 = kani::any();
    kani::assume(claim_credit_amount > 0);
    kani::assume(payout_amount > 0);
    kani::assume(max_overpay_bps <= MAX_SELECTED_ASSET_PAYOUT_OVERPAY_BPS);
    kani::assume(paid_amount <= u64::MAX - 1);
    kani::assume(audit_nonce <= u64::MAX - 1);
    kani::assume(paid_amount <= approved_amount);
    kani::assume(paid_amount <= u64::MAX - claim_credit_amount);
    kani::assume(paid_amount + claim_credit_amount <= approved_amount);
    let mut state = State {
        status: Status::Live,
        protocol_fee_bps: 0,
        emergency_pause: false,
        paid_amount,
        approved_amount,
        withdrawn_fees: 0,
        accrued_fees: 0,
        audit_nonce,
    };
    let args = SettleClaimCaseSelectedAssetArgs {
        claim_credit_amount,
        payout_amount,
        max_overpay_bps,
    };

    assert!(settle_claim_case_selected_asset(&mut state, args));
    assert!(claim_payment_bounded(&state));
}

#[kani::proof]
fn fee_withdrawal_transition_preserves_accrued_fee_bound() {
    let withdrawn_fees: u64 = kani::any();
    let accrued_fees: u64 = kani::any();
    let amount: u64 = kani::any();
    let audit_nonce: u64 = kani::any();
    kani::assume(amount > 0);
    kani::assume(withdrawn_fees <= u64::MAX - 1);
    kani::assume(audit_nonce <= u64::MAX - 1);
    kani::assume(withdrawn_fees <= accrued_fees);
    kani::assume(withdrawn_fees <= u64::MAX - amount);
    kani::assume(withdrawn_fees + amount <= accrued_fees);
    let mut state = State {
        status: Status::Live,
        protocol_fee_bps: 0,
        emergency_pause: false,
        paid_amount: 0,
        approved_amount: 0,
        withdrawn_fees,
        accrued_fees,
        audit_nonce,
    };
    let args = WithdrawArgs { amount };

    assert!(withdraw_protocol_fee_spl(&mut state, args));
    assert!(fee_withdrawals_bounded(&state));
}
