// ---- GENERATED BY QEDGEN VIA scripts/run_qedgen.mjs ----
//
// Proptest harness for the QEDGen-derived state-machine invariants.  These
// tests intentionally call transition functions and invariant predicates rather
// than asserting relationships over locally constructed arguments.

use proptest::prelude::*;

const MAX_CONFIGURED_FEE_BPS: u16 = 9999;
const MAX_SELECTED_ASSET_PAYOUT_OVERPAY_BPS: u16 = 50;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Status {
    Uninitialized,
    Live,
}

#[derive(Debug, Clone, Copy)]
struct State {
    status: Status,
    protocol_fee_bps: u16,
    emergency_pause: bool,
    paid_amount: u64,
    approved_amount: u64,
    withdrawn_fees: u64,
    accrued_fees: u64,
    audit_nonce: u64,
}

#[derive(Debug, Clone, Copy)]
struct InitializeProtocolGovernanceArgs {
    protocol_fee_bps: u16,
    emergency_pause: bool,
}

#[derive(Debug, Clone, Copy)]
struct SettleClaimCaseArgs {
    amount: u64,
}

#[derive(Debug, Clone, Copy)]
struct SettleClaimCaseSelectedAssetArgs {
    claim_credit_amount: u64,
    payout_amount: u64,
    max_overpay_bps: u16,
}

#[derive(Debug, Clone, Copy)]
struct WithdrawArgs {
    amount: u64,
}

fn protocol_fee_bps_bounded(s: &State) -> bool {
    s.protocol_fee_bps <= MAX_CONFIGURED_FEE_BPS
}

fn claim_payment_bounded(s: &State) -> bool {
    s.paid_amount <= s.approved_amount
}

fn fee_withdrawals_bounded(s: &State) -> bool {
    s.withdrawn_fees <= s.accrued_fees
}

fn abstract_state_progress_nonnegative(_s: &State) -> bool {
    true
}

fn initialize_protocol_governance(
    s: &mut State,
    args: InitializeProtocolGovernanceArgs,
) -> bool {
    if s.status != Status::Uninitialized || args.protocol_fee_bps > MAX_CONFIGURED_FEE_BPS {
        return false;
    }

    s.status = Status::Live;
    s.protocol_fee_bps = args.protocol_fee_bps;
    s.emergency_pause = args.emergency_pause;
    s.audit_nonce = 0;
    true
}

fn settle_claim_case(s: &mut State, args: SettleClaimCaseArgs) -> bool {
    if s.status != Status::Live
        || s.emergency_pause
        || args.amount == 0
        || s.paid_amount > u64::MAX - 1
        || s.audit_nonce > u64::MAX - 1
        || s.paid_amount > u64::MAX - args.amount
        || s.paid_amount + args.amount > s.approved_amount
    {
        return false;
    }

    s.paid_amount += 1;
    s.audit_nonce += 1;
    true
}

fn settle_claim_case_selected_asset(
    s: &mut State,
    args: SettleClaimCaseSelectedAssetArgs,
) -> bool {
    if s.status != Status::Live
        || s.emergency_pause
        || args.claim_credit_amount == 0
        || args.payout_amount == 0
        || args.max_overpay_bps > MAX_SELECTED_ASSET_PAYOUT_OVERPAY_BPS
        || s.paid_amount > u64::MAX - 1
        || s.audit_nonce > u64::MAX - 1
        || s.paid_amount > u64::MAX - args.claim_credit_amount
        || s.paid_amount + args.claim_credit_amount > s.approved_amount
    {
        return false;
    }

    s.paid_amount += 1;
    s.audit_nonce += 1;
    true
}

fn withdraw_protocol_fee_spl(s: &mut State, args: WithdrawArgs) -> bool {
    if s.status != Status::Live
        || args.amount == 0
        || s.withdrawn_fees > u64::MAX - 1
        || s.audit_nonce > u64::MAX - 1
        || s.withdrawn_fees > u64::MAX - args.amount
        || s.withdrawn_fees + args.amount > s.accrued_fees
    {
        return false;
    }

    s.withdrawn_fees += 1;
    s.audit_nonce += 1;
    true
}

fn live_state() -> impl Strategy<Value = State> {
    (
        0u16..=MAX_CONFIGURED_FEE_BPS,
        any::<bool>(),
        0u64..=(u64::MAX - 1),
        0u64..=u64::MAX,
        0u64..=(u64::MAX - 1),
        0u64..=u64::MAX,
        0u64..=(u64::MAX - 1),
    )
        .prop_map(
            |(
                protocol_fee_bps,
                emergency_pause,
                paid_amount,
                approved_extra,
                withdrawn_fees,
                accrued_extra,
                audit_nonce,
            )| State {
                status: Status::Live,
                protocol_fee_bps,
                emergency_pause,
                paid_amount,
                approved_amount: paid_amount.saturating_add(approved_extra),
                withdrawn_fees,
                accrued_fees: withdrawn_fees.saturating_add(accrued_extra),
                audit_nonce,
            },
        )
}

proptest! {
    #[test]
    fn initialize_transition_preserves_protocol_fee_bound(
        protocol_fee_bps in 0u16..=MAX_CONFIGURED_FEE_BPS,
        emergency_pause in any::<bool>(),
    ) {
        let mut state = State {
            status: Status::Uninitialized,
            protocol_fee_bps: 0,
            emergency_pause: false,
            paid_amount: 0,
            approved_amount: 0,
            withdrawn_fees: 0,
            accrued_fees: 0,
            audit_nonce: 42,
        };
        let args = InitializeProtocolGovernanceArgs { protocol_fee_bps, emergency_pause };

        prop_assert!(initialize_protocol_governance(&mut state, args));
        prop_assert!(protocol_fee_bps_bounded(&state));
        prop_assert!(abstract_state_progress_nonnegative(&state));
    }

    #[test]
    fn direct_claim_transition_preserves_claim_payment_bound(mut state in live_state(), amount in 1u64..=u64::MAX) {
        state.emergency_pause = false;
        prop_assume!(state.paid_amount <= u64::MAX - amount);
        prop_assume!(state.paid_amount + amount <= state.approved_amount);
        let before_paid = state.paid_amount;
        let args = SettleClaimCaseArgs { amount };

        prop_assert!(settle_claim_case(&mut state, args));
        prop_assert_eq!(state.paid_amount, before_paid + 1);
        prop_assert!(claim_payment_bounded(&state));
    }

    #[test]
    fn selected_asset_claim_transition_preserves_claim_payment_bound(
        mut state in live_state(),
        claim_credit_amount in 1u64..=u64::MAX,
        payout_amount in 1u64..=u64::MAX,
        max_overpay_bps in 0u16..=MAX_SELECTED_ASSET_PAYOUT_OVERPAY_BPS,
    ) {
        state.emergency_pause = false;
        prop_assume!(state.paid_amount <= u64::MAX - claim_credit_amount);
        prop_assume!(state.paid_amount + claim_credit_amount <= state.approved_amount);
        let before_paid = state.paid_amount;
        let args = SettleClaimCaseSelectedAssetArgs {
            claim_credit_amount,
            payout_amount,
            max_overpay_bps,
        };

        prop_assert!(settle_claim_case_selected_asset(&mut state, args));
        prop_assert_eq!(state.paid_amount, before_paid + 1);
        prop_assert!(claim_payment_bounded(&state));
    }

    #[test]
    fn fee_withdrawal_transition_preserves_accrued_fee_bound(mut state in live_state(), amount in 1u64..=u64::MAX) {
        prop_assume!(state.withdrawn_fees <= u64::MAX - amount);
        prop_assume!(state.withdrawn_fees + amount <= state.accrued_fees);
        let before_withdrawn = state.withdrawn_fees;
        let args = WithdrawArgs { amount };

        prop_assert!(withdraw_protocol_fee_spl(&mut state, args));
        prop_assert_eq!(state.withdrawn_fees, before_withdrawn + 1);
        prop_assert!(fee_withdrawals_bounded(&state));
    }
}
